services:
  postgres-container:
    image: postgres:15
    environment:
      POSTGRES_DB: chestionare360
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/chestionare360
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres-container
    ports:
      - "8080:8080"

volumes:
  postgres-data: